### ISSUE TITLE
Message transmission mode not supported on this platform (linux).

### ISSUE THREAD

**Issue by TomShephard** [ganeshsar/UnityPythonMediaPipeAvatar#2]
I have an issue where in unity, the project I get this error. I am on Ubuntu Linux

`PlatformNotSupportedException: Message transmission mode is not supported on this platform.
System.IO.Pipes.NamedPipeServerStream.Create (System.String pipeName, System.IO.Pipes.PipeDirection direction, System.Int32 maxNumberOfServerInstances, System.IO.Pipes.PipeTransmissionMode transmissionMode, System.IO.Pipes.PipeOptions options, System.Int32 inBufferSize, System.Int32 outBufferSize, System.IO.HandleInheritability inheritability) (at <d7b1b8a7919549cdaae04fa24e1ffda0>:0)
System.IO.Pipes.NamedPipeServerStream..ctor (System.String pipeName, System.IO.Pipes.PipeDirection direction, System.Int32 maxNumberOfServerInstances, System.IO.Pipes.PipeTransmissionMode transmissionMode, System.IO.Pipes.PipeOptions options, System.Int32 inBufferSize, System.Int32 outBufferSize, System.IO.HandleInheritability inheritability) (at <d7b1b8a7919549cdaae04fa24e1ffda0>:0)
System.IO.Pipes.NamedPipeServerStream..ctor (System.String pipeName, System.IO.Pipes.PipeDirection direction, System.Int32 maxNumberOfServerInstances, System.IO.Pipes.PipeTransmissionMode transmissionMode) (at <d7b1b8a7919549cdaae04fa24e1ffda0>:0)
(wrapper remoting-invoke-with-check) System.IO.Pipes.NamedPipeServerStream..ctor(string,System.IO.Pipes.PipeDirection,int,System.IO.Pipes.PipeTransmissionMode)
PipeServer.Run () (at Assets/PipeServer.cs:100)
System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <35594092a38441a79b40e2237d5e8762>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <35594092a38441a79b40e2237d5e8762>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <35594092a38441a79b40e2237d5e8762>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) (at <35594092a38441a79b40e2237d5e8762>:0)
System.Threading.ThreadHelper.ThreadStart () (at <35594092a38441a79b40e2237d5e8762>:0)
UnityEngine.<>c:<RegisterUECatcher>b__0_0(Object, UnhandledExceptionEventArgs) (at /home/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnhandledExceptionHandler.bindings.cs:46)`

**Comment by ganeshsar** [comment]
I will need to look into this in more detail. I'll run a VM at some point to see what the issue is in more detail and what can be done about it.

**Comment by ganeshsar** [comment]
Turns out the issue is that NamedPipes aren't supported in the same way on Linux as Windows. That being said, I think I have a solution where I'd run platform-dependent code, still need to test on Mac OS but a patch should be coming soon.

In the future, I'm probably going to shift everything into Unity and ditch the python backend altogether - will see.

**Comment by ganeshsar** [comment]
Okay, so I finally got around to this. I decided to just switch to UDP sockets. These are cross-platform and offer additional advantages such as remotely running mediapipe. Just need to integrate this into all the projects…

**Comment by ganeshsar** [comment]
Okay, latest master should support osx, linux. Let me know how it goes…
