### ISSUE TITLE
How to run this project？

### ISSUE THREAD

**Issue by buzhaodi** [ganeshsar/UnityPythonMediaPipeAvatar#3]
Hello, I am very interested in your project, but I have not come into contact with unity. I opened the project using Unity 2021.3.32f1c1 and ran python main.py. It kept prompting "Waiting for Unity project to run."
Can you tell me how to run this demo? I may not understand "your 5 6 two steps in the readme" thank you

**Comment by ganeshsar** [comment]
Hello, you need to open Sample Scene which can be found by navigating through the folders Scenes/Sample Scene inside of the Unity Editor (double-click Sample Scene). Then press the play button to run the unity project.

**Comment by buzhaodi** [comment]
According to what you said, I successfully ran this project. This is very helpful for my study, thank you very much
